Map<String, String> museos = {
  'Casa Estudio de Diego Rivera y Frida Kahlo':
      'El Museo Casa Estudio Diego Rivera y Frida Kahlo se encuentra en el sur de la Ciudad de México y está dedicado a preservar la memoria del muralista y su esposa; así como al estudio y análisis de su generación artística. ',
  'Casa Estudio Luis Barragán':
      'La Casa-Taller de Luis Barragán, más conocida como Casa Luis Barragán, fue la residencia del arquitecto e ingeniero Luis Barragán Morfín en los años siguientes a la Segunda Guerra Mundial. Cuenta con 1162 metros cuadrados, que se reparten entre la construcción y las áreas verdes, y en su conjunto refleja el estilo arquitectónico de Barragán durante ese periodo.',
  'Centro Cultural Universitario Tlatelolco':
      'El Centro Cultural Universitario Tlatelolco es un recinto multidisciplinario perteneciente a la Universidad Nacional Autónoma de México, orientado a la construcción de formas innovadoras de incidencia pública para la paz, los derechos humanos y el ejercicio de la ciudadanía, a través de la memoria, el pensamiento crítico, la empatía y las manifestaciones artísticas y culturales.',
  'Museo Ex Teresa Arte Actual':
      'El Museo Ex Teresa Arte Actual se encuentra localizado en el Centro Histórico de la Ciudad de México, México. El museo es llamado así porque se encuentra en el inmueble de lo que era anteriormente el templo de Santa Teresa la Antigua y se enfoca en la difusión del arte contemporáneo a través de la investigación y exhibición de prácticas artísticas no objetuales y de proceso entre las que destacan principalmente la instalación, el performance, el arte sonoro, el videoarte y la multimedia en general',
  'Museo Antiguo Colegio de San Ildefonso':
      'El Antiguo Colegio de San Ildefonso es un museo de la Ciudad de México, localizado en el Centro Histórico de Ciudad de México, en el número 16 de la calle Justo Sierra. ',
  'Museo Archivo de la Fotografía':
      'El Museo Archivo de la Fotografía (MAF) es un museo que se dedica a la conservación, investigación y difusión fotográfica. Se ubica en el Centro Histórico de la Ciudad de México en la calle República de Guatemala número 34, esquina con Templo Mayor, el inmueble donde se encuentra es conocido como "La casa de las Ajaracas" y fue construido a fines del siglo XVI.',
  'Museo de Arte Carrillo Gil':
      'El Museo de Arte Carrillo Gil se encuentra localizado en el sur de la Ciudad de México. El museo lleva el nombre del coleccionista doctor Álvar Carrillo Gil y se enfoca principalmente a la difusión de su colección integrada principalmente por trabajos de José Clemente Orozco, David Alfaro Siqueiros y Diego Rivera. El museo además presenta arte contemporáneo y experimental de artistas jóvenes. ',
  'Museo de Arte Moderno':
      'El Museo de Arte Moderno (MAM) es un recinto cultural dedicado principalmente a preservar, estudiar y difundir el arte mexicano producido a partir de la década de 1930. Su sede, ubicada en Paseo de la Reforma, dentro del Bosque de Chapultepec de la Ciudad de México, México, fue inaugurada el 20 de septiembre de 1964, y construida a iniciativa del entonces presidente Adolfo López Mateos, responsable de gran parte de la infraestructura cultural del centro del país.',
  'Museo de Arte Popular':
      'El Museo de Arte Popular es una institución dedicada a promover y preservar el arte popular mexicano. Se localiza en el Centro Histórico de la Ciudad de México en un predio que pertenecía a una vieja estación de bomberos, el museo contiene una colección que incluye tapetes, cerámica, vasos, piñatas, alebrijes, muebles, juguetes, utensilios de cocina, entre otros objetos.',
  'Museo de la Ciudad de México':
      'El Museo de la Ciudad de México es un recinto público ubicado en el antiguo palacio de los condes de Santiago de Calimaya, sobre la avenida Pino Suárez número 30, a tres cuadras de la Plaza de la Constitución (Zócalo). El museo está situado en el recinto que antiguamente fue un hermoso palacio virreinal cuya primera construcción se remonta a 1536. Desde entonces el edificio ha sido remodelado y modificado en varias ocasiones, tanto en su aspecto como en su funcionamiento, sirviendo como palacio de familias nobles, vecindad, locales comerciales y recinto cultural.',
  'Museo de la Caricatura':
      'El Museo de la Caricatura se encuentra localizado en el Centro Histórico de la Ciudad de México, en la calle de Donceles No. 99, enfocándose a la difusión de las obras realizadas por caricaturistas mexicanos. Los visitantes pueden conocer y disfrutar del arte, el humor y la crítica, plasmada a través de los años en la exposición permanente La caricatura en la historia, historia de la caricatura.',
  'Museo Diego Rivera Anahuacalli':
      'Fue diseñado por el exponente del muralismo mexicano Diego Rivera para albergar su vasta colección de piezas precolombinas, una de las más grandes del país, mismas que fue recolectando desde su regreso de Europa en 1920. Retomando características de la arquitectura teotihuacana y mexica, Diego Rivera planeó este espacio, como un sitio donde se llevaran a cabo diversas expresiones del arte como teatro, danza, pintura y música, inmersos en una atmósfera cuya arquitectura es una búsqueda de la esencia de lo mexicano a través de su rico pasado precolombino. ',
  'Museo Dolores Olmedo':
      'El Museo Dolores Olmedo Patiño se encuentra en Xochimilco, en el sur de la Ciudad de México, México. Lleva el nombre de la coleccionista Dolores Olmedo Patiño y se enfoca principalmente a la difusión de la obra de Diego Rivera y Frida Kahlo, resguarda un acervo de aproximadamente 3000 piezas, mismas que periódicamente son rotadas para su exhibición. El acervo del museo incluye aproximadamente 600 piezas prehispánicas procedentes de culturas mesoamericanas, como la olmeca, la mixteca, la zapoteca, la totonaca, la maya, la azteca y de las asentadas en la región de Occidente de México.',
  'Museo del Estanquillo':
      'El museo del Estanquillo se encuentra localizado en el Centro Histórico de la Ciudad de México, México. El museo da cabida a la colección personal del escritor Carlos Monsiváis que abarca pinturas, fotografía, juguetes, álbumes; calendarios, publicidad y libros. ',
  'Museo Experimental El Eco':
      'El Museo Experimental El Eco se encuentra localizado en el centro de la Ciudad de México, México. El museo se enfoca tanto al arte contemporáneo interdisciplinario, como a relacionarlo con el trabajo de Mathias Goeritz, creador del museo.',
  'Foto Museo Cuatro Caminos':
      'El proyecto comenzó a principios de 2012 en lo que anteriormente era una nave industrial que albergaba un fábrica de plásticos en la década de 1940. El financiamiento para su realización se obtuvo a través de fondos de la Fundación Pedro Meyer y del apoyo económico brindado por el Consejo Nacional para la Cultura y las Artes. La remodelación del antiguo espacio estuvo a cargo del arquitecto Mauricio Rocha Iturbide y fue inaugurado el 5 de septiembre de 2015 por Rafael Tovar y de Teresa.',
  'Museo Franz Mayer':
      'El Museo Franz Mayer, localizado en la Ciudad de México, es uno de los museos más importantes de México. Se inauguró en 1986 con la colección privada del empresario Franz Mayer Traumann (1882-1975), de origen alemán. Alberga una de las principales colecciones de artes decorativas de México y presenta exposiciones temporales de diseño y fotografía.',
  'Museo Frida Khalo. Casa Azul':
      'El Museo Frida Kahlo está ubicado en la calle de Londres 247, en uno de los barrios más antiguos y bellos de la Ciudad de México, el centro de Coyoacán. También conocido como la Casa Azul, es de los sitios turísticos y culturales más representativos de la zona; el inmueble perteneció a la familia Kahlo desde 1904 y cuatro años después de la muerte de la pintora, en 1958, fue convertida en museo.',
  'Museo de Geología':
      'El Museo de Geología de la UNAM, ubicado en la Colonia Santa María la Ribera de la Ciudad de México, es un recinto destinado a albergar las colecciones geológicas más importantes de México, es sede de casi todas las sociedades científicas relacionadas con la Geología en el país, así como un sitio de divulgación del conocimiento sobre las ciencias de la Tierra. El Instituto de Geología de la UNAM es la institución que se encarga de resguardarlo.',
  'Museo de Historia Natural':
      'El Museo de Historia Natural es un museo de historia natural situado en la Ciudad de México. Está ubicado en la segunda sección del Bosque de Chapultepec. Mediante sus especímenes en exposición, el museo pretende ofrecer a sus visitantes un resumen de la historia del universo, de la Tierra y del ser humano. Fue fundado originalmente en 1790 como un gabinete de historia natural (en aquella época los gabinetes de curiosidades fueron los precedentes de los actuales museos). Más tarde, y en algunos momentos puntuales de su historia, ha ido cambiando tanto su nombre como su ubicación. Por ejemplo, de 1909 a 1964 se llamó «Museo Nacional de Historia Natural», pero en 1964 pasó a llamarse oficialmente «Museo de Historia Natural», nombre que ha conservado hasta la actualidad.',
  'Museo Indígena':
      'En este museo se exhiben objetos de los pueblos indígenas de México, que datan de 1605 a la fecha e incluyen textiles, cerámica, laca, fibras, juguetes, miniaturas, esculturas, máscaras, arte plumario, cartón y papel, hueso y concha, gráfica y pintura, mobiliario, metales, lapidaria, joyería, talabertería, instrumentos musicales y vidrio. Estas piezas proceden de contextos cotidianos o rituales de los pueblos indígenas de México.',
  'Museo Interactivo de Economía':
      'El Museo Interactivo de Economía, MIDE, situado en la calle de Tacuba en el Centro Histórico de la Ciudad de México, es un museo dedicado a la economía, las finanzas y el desarrollo sustentable. Está ubicado en el Antiguo Convento y hospital de los Betlemitas. Abrió sus puertas en julio del 2006 y fue creado por el Banco de México y diversas instituciones financieras privadas. Depende del Fideicomiso del Espacio Cultural y Educativo Betlemitas y está regido por un Comité Técnico que se reúne anualmente. ',
  'Museo José Luis Cuevas':
      'El Museo José Luis Cuevas y la iglesia de Santa Inés están situados justo al lado de la plaza principal o Zócalo de la Ciudad de México. Inicialmente, ambos formaron parte de un mismo conjunto conventual. El museo se fundó en lo que era la parte residencial del convento de Santa Inés en la época colonial. Este convento fue fundado en 1600 por Diego Caballero y su esposa Inés de Velasco; existió hasta 1861, debido a la ley de nacionalización de la propiedad de la Iglesia, por la cual todos los conventos y monasterios en el país se disolvieron. La iglesia del convento y la sala residencial se separaron. La iglesia de Santa Inés aún mantiene su función original. La sala residencia se convirtió en la propiedad privada, que funcionó principalmente como viviendas hasta que el artista plástico José Luis Cuevas compró la propiedad con la intención de restaurarla y establecer el actual museo dedicado a su arte y al arte contemporáneo de América Latina.',
  'Museo del Juguete Antiguo México':
      'El Museo del Juguete Antiguo México (MUJAM) es una asociación cultural que alberga primordialmente los juguetes más representativos de la cultura mexicana, con ejemplares que datan desde el siglo XIX hasta la década de 1980, aunque también posee piezas de otras partes del mundo. La colección fue iniciada por el arquitecto Roberto Shimizu y abrió sus puertas al público en abril de 2008. El recinto también realiza actividades culturales e imparte talleres interdisciplinarios en torno a las artes y humanidades. El objetivo del museo es rescatar el patrimonio cultural por medio de la preservación de los juguetes que dieron identidad a la cotidianidad de la niñez mexicana.',
  'Museo Jumex':
      'El Museo Jumex, ubicado en la Ciudad de México, es la plataforma principal de acción de Fundación Jumex Arte Contemporáneo, cuyo fundador y presidente es Eugenio López Alonso. Abrió sus puertas al público en noviembre de 2013 como institución dedicada al Arte Contemporáneo con el objetivo de convertirse en un laboratorio para la experimentación e innovación en las artes. A través de sus exposiciones y programas públicos, aspira a posicionarse como institución relevante en el campo del arte al producir, y coproducir en conjunto con otras instituciones, exposiciones e investigaciones originales que familiaricen al público con los conceptos y contextos que informan la producción artística en la actualidad. Durante su primera década, la Fundación Jumex se consolidó como la institución privada sin fines de lucro que apoyó a curadores y artistas que actualmente forman parte del panorama artístico contemporáneo nacional e internacional, y aunque había un público que asistía a las exposiciones en Ecatepec, López Alonso sabía que había que dar un paso más que le permitiera compartir su entusiasmo por el arte contemporáneo con un público más amplio.',
  'Laboratorio Arte Alameda':
      'El Laboratorio Arte Alameda (Ciudad de México) es un espacio dedicado a la exhibición, documentación, producción e investigación de las prácticas artísticas que utilizan y ponen en diálogo la relación arte-tecnología. ',
  'Museo Memoria y Tolerancia':
      'El Museo Memoria y Tolerancia es un recinto museográfico de la Ciudad de México. Abrió sus puertas el 18 de octubre de 2010 y busca difundir el respeto a la diversidad y la tolerancia con base en el recuerdo histórico mediante el uso de exposiciones de genocidios y presentaciones multimedia de los valores a favor de la tolerancia.',
  'Museo de la Mujer':
      'El Museo de la Mujer de México es una institución museística dependiente de la Universidad Nacional Autónoma de México (UNAM) destinada a hacer visible el quehacer histórico de las mujeres en el desarrollo y la construcción de México. Ubicado en el corazón histórico de la Ciudad de México, es el segundo museo de este tipo en América Latina.',
  'Museo Mural Diego Rivera':
      'El Museo Mural Diego Rivera se encuentra localizado en el Centro Histórico de la Ciudad de México, y en él se alberga el mural Sueño de una tarde dominical en la Alameda Central de Diego Rivera. El objetivo del museo consiste en preservar y difundir la obra de Rivera. Asimismo, realiza exposiciones temporales de otros artistas, ciclos de charlas, conciertos y diversas actividades.',
  'Museo Nacional de Antropología':
      'El Museo Nacional de Antropología (MNA) es uno de los recintos museográficos más importantes de México y de América. Está concebido para albergar y exhibir el legado arqueológico de los pueblos de Mesoamérica, así como para dar cuenta de la diversidad étnica actual del país. El edificio actual del MNA fue construido entre 1963 y 1964 en el Bosque de Chapultepec por instrucción del presidente Adolfo López Mateos, diseńado por Pedro Ramírez Vázquez y asistido por los arquitectos Rafael Mijares y Jorge Campuzano. El presidente Adolfo López Mateos lo inauguró el 17 de septiembre de 1964.',
  'Museo Nacional de Arte':
      'El Museo Nacional de Arte (MUNAL) de México se encuentra en el Centro Histórico de la Ciudad de México, en un edificio marcado con el número 8 de la calle Tacuba, en la plaza Manuel Tolsá. Alberga una colección representativa de arte mexicano, desde la era virreinal hasta la década de 1950. ',
  'Museo Trick Eye':
      'Trick Eye es el Museo que engaña a tus ojos, la ilusión óptica 3D museo de arte, es el primer museo del mundo de AR que aplica la tecnología de la realidad aumentada en sus exposiciones para producir vibrantes, emocionantes fotos y vídeos. Los visitantes pueden conocer a un dragón marino que expulsa fuego por la boca mientras estas de pie sobre un puente de troncos, nadar con tiburones ballena mientras estas atrapado en un tanque gigante lleno de ellos, e incluso conocer osos polares mientras está sentado en acantilados de hielo.',
  'Museo Nacional de Culturas Populares':
      'El Museo Nacional de las Culturas Populares está localizado en la Ciudad de México y está dedicado a la diversidad cultural y étnica de México. Esta diversidad no solo abarca a las personas indígenas de México, sino también a sus regiones y estrato socioeconómico. Fue fundado en 1982 por Guillermo Bonfil Batalla en una época en la que el país estaba aceptando y promoviendo oficialmente su diversidad cultural. El museo no contiene una exhibición permanente, está preferentemente enfocado en exhibiciones temporales, conciertos, talleres y otros eventos culturales y educacionales. Este museo promueve la creación de otros museos que promuevan las culturas locales en México. El museo también es la sede del Centro de Información y Documentación Alberto Beltrán, fundado en 1971 para promover la investigación y el conocimiento sobre las etnias indígenas, las artesanías y arte folklórico mexicano. ',
  'Museo del Palacio de Bellas Artes':
      'El Palacio de Bellas Artes es un recinto cultural ubicado en el Centro Histórico de la Ciudad de México, considerado el más importante en la manifestación de las artes en México y una de las casas de ópera más renombradas del mundo. Este ha sido escenario y testigo de impactantes acontecimientos tanto artísticos, como sociales y políticos; su construcción inició al final del mandato de Porfirio Díaz con motivo de la celebración del centenario del inicio de la Independencia de México, sin embargo fue concluido e inaugurado hasta el 29 de noviembre de 1934 debido a la Revolución mexicana.',
  'Museo Nacional de la Acuarela':
      'El Museo Nacional de la Acuarela Alfredo Guati Rojo fue fundado en 1967 por el maestro Alfredo Guati Rojo, quien también se encargó de la dirección del mismo hasta el año de su muerte en 2003. Actualmente el museo se encuentra en una casa privada en el barrio de Santa Catarina, Coyoacán en la Ciudad de México, donde radica desde el año 1987. Fue el primer museo en el mundo que se especializó únicamente en pintura en acuarela, por ello su dedicación gira en torno a dicha técnica. ',
  'Museo Nacional de Historia':
      'El Museo Nacional de Historia de México está ubicado en el Castillo de Chapultepec, en la alcaldía Miguel Hidalgo de la Ciudad de México. Fundado en 1939 por decreto presidencial de Lázaro Cárdenas e inaugurado el 27 de septiembre de 1944, conserva colecciones arqueológicas, históricas, artísticas y patrimoniales de la historia de México desde la época de los mexicas hasta la Revolución mexicana. Cuenta con 12 salas de exhibición permanente y 22 salas con recreaciones históricas dentro del área conocida como Alcázar.',
  'Museo Nacional de la Revolución':
      'El Monumento a la Revolución es una obra arquitectónica y un mausoleo dedicado a la conmemoración de la Revolución mexicana. Es obra del arquitecto Carlos Obregón Santacilia, quien tomó la estructura de la Sala de los Pasos Perdidos del malogrado Palacio Legislativo Federal del arquitecto francés Émile Bénard para edificar el monumento, concluido en 1938. Actualmente es uno de los más simbólicos en la Ciudad de México, y forma parte de un conjunto integrado por el propio monumento, la Plaza de la República y el Museo Nacional de la Revolución. Se localiza en la Colonia Tabacalera de la alcaldía Cuauhtémoc, cerca del Centro Histórico de la Ciudad de México.',
  'Museo Nacional de las Intervenciones':
      'El Museo Nacional de las Intervenciones se encuentra en el exconvento de Churubusco, Coyoacán, Ciudad de México, edificio que cuenta con una antigüedad de más de cuatrocientos años. El museo es administrado por el Instituto Nacional de Antropología e Historia, y el tema del mismo es la historia de las intervenciones extranjeras en México, desde que este se convirtió en un país independiente al firmar su Acta de Independencia el 28 de septiembre de 1821. Algunas de las invasiones militares que muestra la exposición son las realizadas por España, Francia y los Estados Unidos de América durante los siglos XIX y XX.',
  'Museo Numismático Nacional':
      'El Museo Numismático Nacional forma parte de la Casa de Moneda de México, en donde desde el siglo XVII se llevaba a cabo el proceso industrial de separar el oro que venía mezclado con plata de las minas, éste recinto se encuentra en el Centro Histórico, en la antigua Casa del Apartado.',
  'Museo del Objeto del Objeto':
      'El Museo del Objeto (MODO) es un museo inaugurado en 2010 que se ha dedicado a contar historias mediante objetos que han acompañado la vida diaria en México desde hace más de 200 años. Valiosas piezas, artefactos singulares, seleccionadas y agrupadas en exposiciones con la finalidad de mostrar y hacer imaginar o vivir aquellos momentos que, mediante el cariño y la nostalgia, están guardados en la memoria de todos.',
  'Museo Soumaya Plaza Carso':
      'El Museo Soumaya es una institución cultural sin fines de lucro fundada en 1994 que cuenta con tres recintos en la Ciudad de México: Plaza Loreto, Plaza Carso y la Casa Museo Guillermo Tovar de Teresa. Su labor principal es compartir la colección de Fundación Carlos Slim, que ofrece más de 3 siglos de arte americano y europeo, en espacios de encuentro para todos, que motiven la reflexión y el diálogo en el panorama cultural latinoamericano, mediante el compromiso y la acción social. Conserva, resguarda e investiga la colección de arte y promueve exposiciones temporales e itinerantes nacionales e internacionales de diversa índole. El nombre del museo honra la memoria de Soumaya Domit, esposa del empresario y fundador del museo, Carlos Slim Helú, fallecida en 1999.',
  'Museo Tamayo Arte Contemporáneo':
      'El Museo Tamayo Arte Contemporáneo, también conocido como Museo Tamayo o Museo Rufino Tamayo, es un museo localizado dentro del Bosque de Chapultepec, en la Ciudad de México, México. Honra a Rufino Tamayo. Es un museo público dedicado a presentar exposiciones de arte contemporáneo internacional y de su colección de arte moderno y contemporáneo con el fin de enriquecer la experiencia estética y fomentar el sentido crítico de los espectadores. También investiga y difunde en diversos formatos las obras de su colección, así como la obra de Rufino Tamayo.',
  'Museo de las Culturas Pasión por Iztapalapa':
      'Recinto construido en forma de caracol, con una rampa que inicia en la planta baja y llega hasta el quinto piso. Tiene espacios alternos como: La Sala Roja, el Laberinto, la Sala Magna y el espacio donde se exhibe la Semana santa de Iztapalapa. También cuenta con una terraza al aire libre donde se pueden realizar eventos para audiencias de 20 a cuarenta personas. Al final de la rampa, encontramos una sala que tiene las dimensiones similares a la sala de Semana Santa. ',
  'Templo Mayor':
      'El Templo Mayor o Gran Templo de México (denominación empleada por fray Bernardino de Sahagún) es un recinto que comprende una serie de construcciones, edificios, torres (a cada una de estas construcciones piramidales la denomina él torre o cu —éste sería el adoratorio indígena, pudiendo haber varios adoratorios por torre— y fray Toribio de Benavente las describe como una gran cepa cuadrada y esquinada coronada por uno o dos altares) y un patio, el espacio físico donde se ubicaban las mismas, cercado por una pared que contaba con unas puertas que daban acceso a las calzadas principales de la ciudad.',
  'Museo Universitario de Arte Contemporáneo':
      'El Museo Universitario de Arte Contemporáneo (MUAC) de la Universidad Nacional Autónoma de México (UNAM) es el primer museo público creado ex profeso (arquitectura, gestión, museología e interpretación) para el arte contemporáneo en México. Se ubica en el Centro Cultural Universitario, dentro de Ciudad Universitaria de la UNAM.',
  'Museo Universitario del Chopo':
      'El Museo Universitario del Chopo (coloquialmente El Chopo) es un recinto museográfico de la ciudad de México, dedicado a la promoción y difusión del arte contemporáneo. Sus actividades se enmarcan dentro de la Coordinación de Difusión Cultural de la Universidad Nacional Autónoma de México (UNAM). Durante décadas, el Museo del Chopo fue la única opción de arte joven, accesible y de calidad en el centro de la ciudad que logró consolidar un proyecto multidisciplinario reconocido por su carácter plural, crítico e independiente.',
  'Papalote Museo del Niño':
      'El Papalote Museo del Niño se encuentra localizado en el bosque de Chapultepec (2a. Sección) de la Ciudad de México, México. El museo está enfocado al aprendizaje, la comunicación y convivencia de los niños a través de exposiciones interactivas de ciencia, tecnología y arte. Es un museo interactivo cuya tarea es propiciar el aprendizaje significativo a través de experiencias que acercan al niño a comprender el mundo que le rodea por medio de herramientas que le permiten experimentar, participar, conocer, explicar, vivir, sentir y cuestionar su entorno.',
  'Sala de Arte Público Siqueiros':
      'La Sala de Arte Público Siqueiros es un museo localizado en Polanco, en la Ciudad de México. La sala tiene como objetivo preservar y difundir la obra del pintor David Alfaro Siqueiros, y presentar arte contemporáneo de diferentes disciplinas. El inmueble fue durante mucho tiempo la casa del pintor, hasta que decidió convertirla en un museo y el 29 de enero de 1969 fue la inauguración oficial; durante esta época Siqueiros seguía siendo el propietario. Antes de su muerte (acaecida el 6 de enero de 1974) decide formalmente que la casa y su acervo perteneciera al patrimonio del pueblo de México. En la actualidad el museo pertenece al Instituto Nacional de Bellas Artes.',
  'Universum Museo de las Ciencias':
      'Universum, el Museo de las Ciencias de la Universidad de México (UNAM), es el primer museo en México dedicado a promover conocimiento a los ciudadanos y extranjero y promover la ciencia y tecnología al público dentro del ámbito universitario y escolar, ya que en general le precede el Museo Tecnológico de la Comisión Federal de Electricidad, así, como brindar apoyo a proyectos de ciencia de las universidades. Se inauguró el 12 de diciembre de 1992 en Ciudad Universitaria, en la Ciudad de México. Actualmente cuenta con trece salas, las cuales se encuentran divididas por una temática diferente. Es un museo que trabaja con colaboradores externos y con entidades privadas que ayudan al desarrollo de las exposiciones permanentes, temporales y a la gestión de otros museos de ciencias en diversos estados del país.',
};
